### ISSUE TITLE
Add expires option to set-cookie header for authenticate mutation

### ISSUE THREAD

**Issue by kkerti** [arrrrny/vendure-plugin-firebase-auth#1]
### Description
When using the NativeAuthenticationStrategy from vendure core, the authenticate mutation returns not only the User, but an AuthenticatedSession. Although I don't understand fully yet the underlying mechanism how this results in a fully populated 'set-cookie' return header, that mutation returns a proper `set-cookie` header with `expires` and other necessary cookie option fields. It's a neat way to save the session and ssig cookies storefront side.

### Request
To avoid extra network roundtrip, and make this plugin work more akin to vendure core's strategy, add the necessary cookie options to the returned header from the `authenticate` mutation.

**Comment by arrrrny** [comment]
This is a setting in Vendure config under cookieOptions.
https://docs.vendure.io/reference/typescript-api/auth/cookie-options
You can use max-age in milliseconds as the same value of your session duration

<img width="468" alt="Screenshot 2024-08-15 at 9 05 25 AM" src="https://github.com/user-attachments/assets/5041d8f3-b1b5-412e-97ab-3b460a01b1c8">


![Screenshot 2024-08-15 at 9 05 40 AM](https://github.com/user-attachments/assets/9aed7fb9-6604-41c1-8c70-2181a596eeb9)
